PREFIX doo: <https://decisionoperations.org/ontology/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT ?assumption ?until WHERE { ?assumption a doo:Assumption ; doo:validUntil ?until . FILTER(?until < NOW()) }
