name: "KPI Portfolio — Data Integration"
description: "Work on connectors, schemas, adapters, fixtures, ingestion pathways."
title: "[KPI][Data Integration] "
labels: ["kpi:data_integration"]
body:
  - type: markdown
    attributes:
      value: |
        Add one `sev:*` and one `type:*` label after creation.
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options: ["sev:P0", "sev:P1", "sev:P2", "sev:P3"]
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: Type
      options: ["type:feature", "type:bug", "type:debt", "type:doc"]
    validations:
      required: true
  - type: textarea
    id: objective
    attributes:
      label: Objective
    validations:
      required: true
  - type: textarea
    id: deliverables
    attributes:
      label: Deliverables
    validations:
      required: true
  - type: textarea
    id: proof
    attributes:
      label: Proof / Verification
    validations:
      required: true
