#!/usr/bin/env python3
"""Export FastAPI OpenAPI spec + static Redoc docs for dashboard API."""

from __future__ import annotations

import json
from pathlib import Path


def _enrich_openapi(spec: dict) -> dict:
    paths = spec.get("paths", {})
    for path, operations in paths.items():
        if not isinstance(operations, dict):
            continue
        for method, op in operations.items():
            if method.lower() not in {"get", "post", "put", "patch", "delete"}:
                continue
            if not isinstance(op, dict):
                continue

            if not op.get("summary"):
                op["summary"] = f"{method.upper()} {path}"
            if not op.get("description"):
                op["description"] = f"Autogenerated reference for `{method.upper()} {path}`."

            req = op.get("requestBody")
            if isinstance(req, dict):
                content = req.get("content", {})
                json_ct = content.get("application/json")
                if isinstance(json_ct, dict):
                    if "examples" not in json_ct and "example" not in json_ct:
                        json_ct["example"] = {}
                    if "schema" not in json_ct:
                        json_ct["schema"] = {"type": "object"}

            responses = op.get("responses", {})
            if isinstance(responses, dict):
                for resp in responses.values():
                    if not isinstance(resp, dict):
                        continue
                    content = resp.get("content")
                    if not isinstance(content, dict):
                        continue
                    json_ct = content.get("application/json")
                    if isinstance(json_ct, dict) and "schema" not in json_ct:
                        json_ct["schema"] = {"type": "object"}
    return spec


def main() -> int:
    from dashboard.api_server import app

    root = Path(__file__).resolve().parents[1]
    out_dir = root / "docs" / "api"
    out_dir.mkdir(parents=True, exist_ok=True)

    spec = _enrich_openapi(app.openapi())
    spec_path = out_dir / "openapi.json"
    spec_path.write_text(json.dumps(spec, indent=2) + "\n", encoding="utf-8")

    redoc_html = """<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>DeepSigma API Reference</title>
    <style>
      body { margin: 0; padding: 0; }
      .top {
        font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial;
        padding: 12px 16px;
        background: #0b1220;
        color: #e6edf7;
      }
      .top a { color: #9dc1ff; text-decoration: none; }
    </style>
  </head>
  <body>
    <div class="top">
      DeepSigma API Reference
      ·
      <a href="./openapi.json">openapi.json</a>
    </div>
    <redoc spec-url="./openapi.json"></redoc>
    <script src="https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js"></script>
  </body>
</html>
"""
    (out_dir / "index.html").write_text(redoc_html, encoding="utf-8")

    readme = """# API Reference

- OpenAPI spec: `openapi.json`
- Static docs: `index.html` (Redoc)

Regenerate from code:

```bash
python scripts/export_openapi.py
```
"""
    (out_dir / "README.md").write_text(readme, encoding="utf-8")

    print(f"Wrote: {spec_path}")
    print(f"Wrote: {out_dir / 'index.html'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
